"""Update available_dates type to ARRAY

Revision ID: 0f3df8e79fd7
Revises: 875e638d9791
Create Date: 2025-03-30 00:45:41.743683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3df8e79fd7'
down_revision: Union[str, None] = '875e638d9791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 