"""Add guest fields to travel requests

Revision ID: c2500936315a
Revises: b5644fd168c9
Create Date: 2025-03-31 17:39:17.742045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2500936315a'
down_revision: Union[str, None] = 'b5644fd168c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_requests', sa.Column('guest_name', sa.String(), nullable=True))
    op.add_column('travel_requests', sa.Column('guest_email', sa.String(), nullable=True))
    op.add_column('travel_requests', sa.Column('guest_phone', sa.String(), nullable=True))
    op.add_column('travel_requests', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_requests', 'comment')
    op.drop_column('travel_requests', 'guest_phone')
    op.drop_column('travel_requests', 'guest_email')
    op.drop_column('travel_requests', 'guest_name')
    # ### end Alembic commands ### 